<?php

/**
 * @file
 * Attaching js.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Alter custom block forms rendered by Block Content and Layout Builder.
 *
 * E.g. Alter block forms for 'block_content' and 'inline_block' plugins.
 *
 * @param array $form
 *   Nested array of form elements that comprise the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 * @param string $block_type
 *   The machine name of the custom block bundle.
 */
function ezcontent_block_cards_block_type_form_alter(array &$form, FormStateInterface &$form_state, string $block_type) {
  if ($block_type == 'cards') {
    $form['#attached']['library'][] = 'ezcontent_block_cards/ezcontent_block_cards';
  }
}
