<?php

/**
 * @file
 * Attaching js.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function ezcontent_block_cards_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'layout_builder_add_block') {
    $blockComponent = $form_state->get('layout_builder__component');
    if ($blockComponent->getPluginId() === 'inline_block:cards') {
      $form['#attached']['library'][] = 'ezcontent_block_cards/ezcontent_block_cards';
    }
  }
}
