<?php

use Drupal\Core\Entity\EntityForm;
use Drupal\Core\Url;
use Drupal\ezcontent_preview\Utils;

/**
 * Implements hook_views_data_alter()
 */
function ezcontent_preview_views_data_alter(&$data) {
	$label = 'Published or Access Unpublished Token';
	$data['node']['published_access_unpublished_token'] = array(
		'title' => $label,
		'filter' => array(
			'title' => $label,
			'help' => t('Published or Access unpublish content with token'),
			'field' => 'nid',
			'id' => 'published_access_unpublished_token'
		),
	);
}
