<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function ezcontent_embed_preprocess_paragraph__embed(&$variables) {
  $variables['#attached']['library'][] = 'ezcontent_embed/ezcontent_embed_css';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ezcontent_embed_preprocess_block(&$variables) {
  if (isset($variables['elements']['content']['#block_content'])) {
    $bundle = $variables['elements']['content']['#block_content']->bundle();
    if ($bundle === 'embed_block') {
      $variables['#attached']['library'][] = 'ezcontent_embed/ezcontent_embed_css';
    }
  }
}
